### ISSUE TITLE
cisco.dnac.dnacaap_management_execution_status_info not resolving in playbook

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacenter-ansible#104]
**Prerequisites**
* [Y ] Have you tested the operation in the API directly?
* [Y] Do you have the latest Ansible collection version?
* [Y] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
cisco.dnac.cisco.dnac.dnacaap_management_execution_status_info is not getting resolved in playbook.
---
- name: Configure device credentials on Cisco DNA Center
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - "{{ VARFILEPATH }}/input_global_ippools.yml"
    - "{{ CLUSTERFILE }}"
  tasks:
    - name: Create Global IP Pools
      no_log: true
      cisco.dnac.global_pool:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        state: present
        settings:
          ippool: "{{ global_ippools}}"
      register: global_ippools_result
    - name: Print Global IP Pools Result
      debug:
        msg: "{{ global_ippools_result }}"
    - name: Check Execution Status
      cisco.dnac.cisco.dnac.dnacaap_management_execution_status_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_version: "{{dnac_version}}"
        dnac_debug: "{{dnac_debug}}"
        state: present
        executionId: " {{ global_ippools_result.dnac_response.executionId }}"

Error received:
2023-06-09T05:17:58: %ANSIBLELOGER-INFO: run failed events: False
2023-06-09T05:17:58: %ANSIBLELOGER-INFO: Run result status None
2023-06-09T05:17:58: %ANSIBLELOGER-ERROR: 
2023-06-09T05:17:58: %ANSIBLELOGER-INFO: ERROR! couldn't resolve module/action 'cisco.dnac.cisco.dnac.dnacaap_management_execution_status_info'. This often indicates a misspelling, missing collection, or incorrect module path.
2023-06-09T05:17:58: %ANSIBLELOGER-INFO: 
2023-06-09T05:17:58: %ANSIBLELOGER-INFO: The error appears to be in '/Users/pawansingh/dnac_auto/Guardian/Hulk/dnac-auto/dnac_ansible/playbooks/globalippools/project/globalippools.yml': line 27, col

**Expected behavior**

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Ansible Version:
* Collection version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
@DNACENSolutions , please review your `dnac_version` and your `Collection version`, I test the module and it didn't give me a problem.

**Comment by DNACENSolutions** [comment]
Upgraded to cisco.dnac:6.7.2
The the module is getting resolved now. 

TASK [Check Execution Status] **************************************************
Attempt 1

Request
	URL: https://10.195.227.14:443/dna/intent/api/v1/dnacaap/management/execution-status/077311c2-6ae7-4155-81ae-7d04b5cb3cfb
	Method: GET
	Headers: 
		User-Agent: python-requests/2.28.2
		Accept-Encoding: gzip, deflate
		Accept: */*
		Connection: keep-alive
		X-Auth-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDdmMTAxOWJiNjgwYzVmYjE1ZmMxODIiLCJhdXRoU291cmNlIjoiaW50ZXJuYWwiLCJ0ZW5hbnROYW1lIjoiVE5UMCIsInJvbGVzIjpbIjY0N2YxMDE4YmI2ODBjNWZiMTVmYzE4MSJdLCJ0ZW5hbnRJZCI6IjY0N2YxMDE3YmI2ODBjNWZiMTVmYzE3ZiIsImV4cCI6MTY4Njc5MTM2NywiaWF0IjoxNjg2Nzg3NzY3LCJqdGkiOiJkYzZhMWFjZS0zYjY3LTQ4YTMtOWEyZC1jZWZjZDg1MTU4MTciLCJ1c2VybmFtZSI6ImFkbWluIn0.X1ngDQ70s1bJ6omRkX_8wpAuBVw0JzF2Y-AKCXHzCXaTRcNfwONeQg5efNNu-Kvw75Dw_QEE5f2Pap7Z-Wvf-AgV4bYYnG2PA4wTPJIA1T6dTWzbIntcrVeUFbXYjZkyyxrNjiR1gPRo6Tf72Tsgd0EuMzs-62N08Ikir2y63xzHIKd0ddLeBzlWkVzTNwCzw0ov5W2HOHnJiQ3zisLsGXMvImXy1dSYW2ENgk0sfnFffMD6Tm0ejKBie5p-73LLMPVrtiQV_LEs2yV4xg8-eBMt02WD26c33LJMgIBX7KJ9KkMkIBE9X_fU-tCZOw7zv7hEoajUu3Y55QDWnnhgtA
		Content-type: application/json;charset=utf-8
	Params:
              {}

Response
	Status: 200 - OK
	Headers: 
		Content-Type: application/json
		Content-Length: 372
		Connection: keep-alive
		Info: This API is deprecated. Please use the URI : /dnacaap/management/executions/status/{bapiExecutionId}
		Date: Thu, 15 Jun 2023 00:09:28 GMT
		x-request-id: 3a5edbcf4ed3f1127c378eb14d9a9783
		Via: api-gateway
		Cache-Control: no-store
		Pragma: no-cache
		Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:
		X-Content-Type-Options: nosniff
		X-XSS-Protection: 1
		Strict-Transport-Security: max-age=31536000; includeSubDomains
		X-Frame-Options: SAMEORIGIN
	Body:
             {
                 "bapiKey": "f793-192a-43da-bed9",
                 "bapiName": "Create Global Pool",
                 "bapiExecutionId": "077311c2-6ae7-4155-81ae-7d04b5cb3cfb",
                 "startTime": "Thu Jun 15 00:09:27 UTC 2023",
                 "startTimeEpoch": 1686787767001,
                 "endTimeEpoch": 0,
             }
ok: [localhost]
