### ISSUE TITLE
site_intent module success for first time when site was not existing, fails if site aleady exist in dnac.

### ISSUE THREAD

**Issue by DNACENSolutions** [cisco-en-programmability/dnacenter-ansible#106]
**Prerequisites**
* [ ] Have you tested the operation in the API directly?
* [y ] Do you have the latest Ansible collection version?
* [y ] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
When we rerun the playbook to create a building, run fails. we Noticed that it is trying to update the site even through there is no change in the site data. and the request fails from dnac side. if the content of the site is same, we don;t need to update it.

Failed logs:
TASK [Create Sites Through Site Intent API] **********************************************************************************************************************************************************
task path: /Users/pawansingh/dnac_auto/Guardian/Hulk/dnac-auto/dnac_ansible/playbooks/siteheirarchy/project/siteheirarchy.yml:22
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: pawansingh
<127.0.0.1> EXEC /bin/sh -c 'echo ~pawansingh && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/pawansingh/.ansible/tmp `"&& mkdir "` echo /Users/pawansingh/.ansible/tmp/ansible-tmp-1686529772.028372-79297-46677134068076 `" && echo ansible-tmp-1686529772.028372-79297-46677134068076="` echo /Users/pawansingh/.ansible/tmp/ansible-tmp-1686529772.028372-79297-46677134068076 `" ) && sleep 0'
Using module file /Users/pawansingh/.ansible/collections/ansible_collections/cisco/dnac/plugins/modules/site_intent.py
<127.0.0.1> PUT /Users/pawansingh/.ansible/tmp/ansible-local-79273ghhvjs8g/tmputb5_54y TO /Users/pawansingh/.ansible/tmp/ansible-tmp-1686529772.028372-79297-46677134068076/AnsiballZ_site_intent.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/pawansingh/.ansible/tmp/ansible-tmp-1686529772.028372-79297-46677134068076/ /Users/pawansingh/.ansible/tmp/ansible-tmp-1686529772.028372-79297-46677134068076/AnsiballZ_site_intent.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/pawansingh/dnac_auto/Guardian/pyatsenv311/bin/python3.11 /Users/pawansingh/.ansible/tmp/ansible-tmp-1686529772.028372-79297-46677134068076/AnsiballZ_site_intent.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/pawansingh/.ansible/tmp/ansible-tmp-1686529772.028372-79297-46677134068076/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "config": [
                {
                    "site": {
                        "building": {
                            "address": "McCarthy Blvd, San Jose, California 95131, United States",
                            "country": "United States",
                            "latitude": 12.933971097851867,
                            "longitude": 80.24676818041894,
                            "name": "BLD22",
                            "parentName": "Global/USA/SAN JOSE"
                        }
                    },
                    "type": "building"
                }
            ],
            "dnac_debug": true,
            "dnac_host": "10.195.243.53",
            "dnac_log": false,
            "dnac_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "dnac_port": "443",
            "dnac_username": "admin",
            "dnac_verify": false,
            "dnac_version": "2.3.5.3",
            "state": "merged",
            "validate_response_schema": true
        }
    },
    "msg": "\"sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\"",
    "response": {
        "bapiError": "\"sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\"",
        "bapiExecutionId": "697e8502-ffed-4217-8616-c1c7811487d6",
        "bapiKey": "eeb7-eb4b-4bd8-a1dd",
        "bapiName": "Update Site",
        "endTime": "Mon Jun 12 00:29:44 UTC 2023",
        "endTimeEpoch": 1686529784890,
        "runtimeInstanceId": "DNACP_Runtime_291e79f6-e853-4abe-95d6-2835bce562bd",
        "startTime": "Mon Jun 12 00:29:34 UTC 2023",
        "startTimeEpoch": 1686529774519,
        "status": "FAILURE",
        "timeDuration": 10371
    }
}

PLAY RECAP *******************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

The second issue:  If we have more then one building in the list, it create only the last building in the list and does not create all the sites from the list.

**Expected behavior**

**Screenshots**
Please provide an screenshot of the successful API call with cuRL, Postman, etc.

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: 
* Ansible Version:
* Collection version:
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
@madhansansel could you review this one?
