### ISSUE TITLE
cisco.dnac.application_sets module with state="absent" have issue with input

### ISSUE THREAD

**Issue by datcpham** [cisco-en-programmability/dnacenter-ansible#122]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Ansible collection version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
In cisco.dnac.application_sets module, when delete existing application-set by it’s id, it returns an error with a code.

Example module in documentation:
```python
- name: Delete all
  cisco.dnac.application_sets:
    dnac_host: "{{dnac_host}}"
    dnac_username: "{{dnac_username}}"
    dnac_password: "{{dnac_password}}"
    dnac_verify: "{{dnac_verify}}"
    dnac_port: "{{dnac_port}}"
    dnac_version: "{{dnac_version}}"
    dnac_debug: "{{dnac_debug}}"
    state: absent
    id: string
``` 
The playbook we play:
```python
- name: Delete application set by id
  cisco.dnac.application_sets:
    <<: *dnac_login
    state: absent
    id: "{{ application_set_id }}"
``` 
And the error we are receiving...
```html
TASK [Delete application set by id] *********************************************************************************************************************************************************************
task path: /auto/dna-sol/ws/datcpham/dnac-auto/dnac_ansible/playbooks/application/application.yml:81
The full traceback is:
Traceback (most recent call last):
  File "/auto/dna-sol/pyats-ws/pyats-datcpham1/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 158, in run
    res = self._execute()
  File "/auto/dna-sol/pyats-ws/pyats-datcpham1/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 651, in _execute
    result = self._handler.run(task_vars=vars_copy)
  File "/users/datcpham/.ansible/collections/ansible_collections/cisco/dnac/plugins/action/application_sets.py", line 217, in run
    (obj_exists, prev_obj) = obj.exists()
  File "/users/datcpham/.ansible/collections/ansible_collections/cisco/dnac/plugins/action/application_sets.py", line 113, in exists
    name = self.new_object.get("name") or requested_obj.get("name")
AttributeError: 'NoneType' object has no attribute 'get'
fatal: [dnac1]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
``` 
Therefore, I temporarily added a payload name to the task, and it ran successfully:
```python
- name: Delete application set by id
  cisco.dnac.application_sets:
    <<: *dnac_login
    state: absent
    id: "{{ application_set_id }}"
    payload:
    - name: null
``` 
It has been successfully deleted:
```html
TASK [Delete application set by id] *********************************************************************************************************************************************************************
task path: /auto/dna-sol/ws/datcpham/dnac-auto/dnac_ansible/playbooks/application/application.yml:81
changed: [dnac1] => {
    "changed": true,
    "dnac_response": {
        "response": {
            "taskId": "018b4c39-2784-7b8b-ac8e-082327e99384",
            "url": "/api/v1/task/018b4c39-2784-7b8b-ac8e-082327e99384"
        },
        "version": "1.0"
    },
    "result": "Object deleted"
}
``` 

**Expected behavior**
It should run successfully with the correct parameters as mentioned in the documentation (we only need dnac_login, state=absent, and id as input parameters) to perform the deletion task.

**Screenshots**
![image](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/148523188/903265c3-cd9c-4700-84c6-28e756690c94)
![image](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/148523188/1f1a19db-105d-4e07-96b7-382f23a22a54)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: Version 2.3.7.3
* Ansible Version: 6.7.6
* Collection version: 2.6.9
* OS Version: 

**Additional context**

**Comment by HongPhatTL** [comment]
@datcpham Please check the release changes from v6.5.1 to v6.5.2 :  
https://github.com/cisco-en-programmability/dnacenter-ansible/compare/v6.5.1...v6.5.2#diff-640505ca6c5997dbb9227788f0a43a6a3f564167b119782e60f336543010829d
in `plugins/action/application_sets.py`

**Comment by fmunozmiranda** [comment]
Fixed in current version.
