### ISSUE TITLE
The parameter in the document does not match with the parameter in the module (cisco.dnac.swim_intent module)

### ISSUE THREAD

**Issue by datcpham** [cisco-en-programmability/dnacenter-ansible#123]
**Prerequisites**
* [x] Have you tested the operation in the API directly?
* [x] Do you have the latest Ansible collection version?
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.

**Describe the bug**
In cisco.dnac.swim_intent module, param deviceIPAddress (document) not mismatch param deviceIpAddress (module)

**Expected behavior**
Parameter get Device IP address in document (deviceIPAddress) need match with Parameter get Device IP address in module (deviceIpAddress)

**Screenshots**
![image](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/148523188/6d4a57a0-c157-4dca-a30a-b9231c5dc196)
![image](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/148523188/8d5453b7-6e0b-41ba-b345-b440e1dae8cc)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: Version 2.3.7.3
* Ansible Version: 6.7.6
* Collection version: 2.6.9
* OS Version: 

**Additional context**

**Comment by fmunozmiranda** [comment]
@madhansansel could you please review this?

**Comment by madhansansel** [comment]
@datcpham, it is fixed in mainline. You can check and close this.

**Comment by datcpham** [comment]
Closed
