### ISSUE TITLE
Issue in cisco.dnac.sda_virtual_network_v2 while creating a virtual network

### ISSUE THREAD

**Issue by kaoutherab** [cisco-en-programmability/dnacenter-ansible#13]
The following task:
  - name: Create Virtual Network
    cisco.dnac.sda_virtual_network_v2:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      state: present
      scalableGroupNames:
      - "test"
      virtualNetworkName: "GUEST_VN"
      virtualNetworkType: "GUEST"
gives this error:
"description": "isGuestVirtualNetwork not found in request json object."

It seems that the attribute "isGuestVirtualNetwork" is missing

**Comment by jbogarin** [comment]
From what we saw, it looks like a documentation bug or API bug from Cisco DNA Center. I will try to let them know about it.

![Screen Shot 2021-09-20 at 11 40 27](https://user-images.githubusercontent.com/4792616/134048707-9ae2f586-18c2-4211-87be-6150c5896297.png)

**Comment by kaoutherab** [comment]
This issue seems a DNAC Platform API documentation issue. As there seem to be a missing attribute for the request to succeed.
