### ISSUE TITLE
FR: Restore Automation Hub signed status for further versions

### ISSUE THREAD

**Issue by wastorga** [cisco-en-programmability/dnacenter-ansible#132]
**Is your feature request related to a problem? Please describe.**
Versions [cisco.dnac v6.8.0](https://console.redhat.com/preview/ansible/automation-hub/repo/staging/cisco/dnac/?version=6.8.0) and [v6.8.1](https://console.redhat.com/preview/ansible/automation-hub/repo/staging/cisco/dnac/?version=6.8.1) are up but they are not signed.

The warnings from the Automation Hub are found in the 'Additional context' section

**Describe the solution you'd like**
1. Restructure the problematic playbooks, 
- use vars instead 
- rename file device_details.yml to device_details.template (delete the device_details.yml, add .gitignore, and add the device_details.template)

2. Use ASCII quotes instead of Unicode quotes.

**Describe alternatives you've considered**

**Additional context**
<img width="1097" alt="Screenshot 2023-11-20 at 18 57 38" src="https://github.com/cisco-en-programmability/dnacenter-ansible/assets/53057769/0aa1a46d-ab45-4307-ab05-997576aa3870">

<img width="731" alt="Screenshot 2023-11-20 at 18 58 05" src="https://github.com/cisco-en-programmability/dnacenter-ansible/assets/53057769/8b0d1f1d-ac90-41d0-ad43-81d28e5d41b1">

**Comment by madhansansel** [comment]
@wastorga  Can you please close this issue? We committed the changes in mainline.
