### ISSUE TITLE
Bug: pnp_device_claim_to_site has incorrect argument_spec for configInfo

### ISSUE THREAD

**Issue by aoforb** [cisco-en-programmability/dnacenter-ansible#134]
**Describe the bug**
Module pnp_device_claim_to_site has incorrect argument_spec for `configInfo`. DNAC is expecting a `dict` not a `list`.
`ansible/blob/main/plugins/action/pnp_device_claim_to_site.py`

**Screenshots**
![image](https://github.com/cisco-en-programmability/dnacenter-ansible/assets/146780854/016b58ac-d39a-449f-9184-8e3af6ea1938)

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch:  2.3.5.3
* 
ansible [core 2.14.5]
python version: 3.10.12 

**Additional context**
Please see issue with dnacentersdk
https://github.com/cisco-en-programmability/dnacentersdk/issues/140

**Comment by fmunozmiranda** [comment]
Changed.
