### ISSUE TITLE
Issue in cisco.dnac.wireless_enterprise_ssid

### ISSUE THREAD

**Issue by kaoutherab** [cisco-en-programmability/dnacenter-ansible#14]
the task to create wireless SSID sends a  GET request:

ASK [Create Wirelesss Enterprise SSID] ************************************************************************************************
task path: /Users/kabrougu/github3/cisco_cloud_labs/domains/SDA/workflow/dnacenter-ansible/playbooks/myplaybook.yml:379
Attempt 1

Request
	URL: https://x.x.x.x:443/dna/intent/api/v1/enterprise-ssid
	Method: GET
	Headers:

**Comment by kaoutherab** [comment]
This issue is "Ansible Module" issue. Everytime I try to create an ENterprise SSID, if we have already an enterprise SSID created in DNAC, then ansible returns "result": "Object already present". If no SSID created then the ansible module throughs an error.

The correspondent API in DNAC Platform APIs is returning a different behavior. Based on the payload expected, it keeps returning invalid JSON.

Below is the payload test:

{
    "name": "test999_pop",
    "securityLevel": "wpa2_enterprise",
    "passphrase": "public123",
    "enableFastLane": false,
    "enableMACFiltering": false,
    "trafficType": "voicedata",
    "radioPolicy": "Dual band operation (2.4GHz and 5GHz)",
    "enableBroadcastSSID": true,
    "fastTransition": "Adaptive",
    "enableSessionTimeOut": true,
    "sessionTimeOut": 1800,
    "enableClientExclusion": true,
    "clientExclusionTimeout": 180,
    "enableBasicServiceSetMaxIdle": true,
    "basicServiceSetClientIdleTimeout": 300,
    "enableDirectedMulticastService": true,
    "enableNeighborList": true,
    "mfpClientProtection": "Optional"
}

**Comment by wastorga** [comment]
I'm unable to replicate the issue in the current environment.
The current environment has the following requirements: dnacentersdk==2.3.2 and cisco.dnac>=3.1.6

Before cisco.dnac 3.1.6, it was an issue.

Feel free to reopen if the problem still exists. Thank you.
