### ISSUE TITLE
Collection must be made compatible with newly released ansible.utils 4.0.0 ASAP

### ISSUE THREAD

**Issue by felixfontein** [cisco-en-programmability/dnacenter-ansible#160]
Currently the collection requires ansible.utils < 4.0.0, but ansible.utils 4.0.0 has been released.

This is a violation of the Dependency rules of the Ansible inclusion requirements (https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#collection-dependencies). If this isn't fixed on time, this collection will be removed from Ansible 10 as a consequence.

**Comment by fmunozmiranda** [comment]
In new update requirements were updated. Let us know if something else is needed.

**Comment by felixfontein** [comment]
Thanks!
