### ISSUE TITLE
cisco.dnac 6.24.0 is not tagged

### ISSUE THREAD

**Issue by mariolenz** [cisco-en-programmability/dnacenter-ansible#205]
Hi! As part of the ansible community package release process, we've determined that version 6.10.0 of cisco.dnac was released to Ansible Galaxy but not properly tagged in this Git repository. This violates the [repository management](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#repository-management) section of the Collection Requirements:

> * Every collection MUST have a public Git repository.
> * Releases of the collection MUST be tagged in its repository.
>   * The git utility with the tag argument MUST be used to tag the releases.
>   * The tag name MUST exactly match the Galaxy version number.
>   * Tag names MAY have a v prefix.
>   * Tag names MUST have a consistent format from release to release.
> * Collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection’s Git repository as that release.
>   * Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

If the collection maintainers do not respond to this issue within a reasonable a amount of time, the collection is subject to [Removal from ansible](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_package_removal.html#collections-not-satisfying-the-collection-requirements).

**Comment by felixfontein** [comment]
Ping @JosePabloOcampo1212.

**Comment by JosePabloOcampo1212** [comment]
Done, the tagging is now done. Thanks for the reminder.

**Comment by felixfontein** [comment]
Thanks a lot!

**Comment by mariolenz** [comment]
Thanks @JosePabloOcampo1212!
