### ISSUE TITLE
create global ip pood is not work - report id is required

### ISSUE THREAD

**Issue by jianm12007** [cisco-en-programmability/dnacenter-ansible#21]
below the playbook used for create global ip pools
-----------------------------------------------------
---
# Create global IP Pool.
- hosts: dnac_servers
  vars_files:
    - vars.yml
  connection: local
  gather_facts: no
  
  tasks:
  - name: Create Global IP Pool
    cisco.dnac.global_pool:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      state: "present"
      settings:
        ippool:
        - ipPoolName: "HQ_Pool_v4"
          type: "Generic"
          IpAddressSpace: "IPv4"
          ipPoolCidr: "100.0.0.0/16"
--------------------------------------------------
below is the error message:

task path: /Users/jianm/ansible/global-ippool-create.yml:10
fatal: [10.74.83.21]: FAILED! => {
    "changed": false,
    "msg": "['state is present but any of the following are missing: id']"
}
---------------------------------------------------
I have tried using API directly from DNAC. It works fine. And create global IP pool should not ask for a id. id is used for delete pools.

**Comment by jianm12007** [comment]
I add the id with blank string. It works. But this DNAC API do not need the ID parameter to create the IP Pools.

---
# Create global IP Pool.
- hosts: dnac_servers
  vars_files:
    - vars.yml
  connection: local
  gather_facts: no
  
  tasks:
  - name: create test
    cisco.dnac.global_pool:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      state: present
      settings:
        ippool:
        - IpAddressSpace: "IPv4"
          ipPoolCidr: "100.1.0.0/16"
          ipPoolName: "HQ_100_1_0_0"
          type: "Generic"
      id: ""

**Comment by wastorga** [comment]
New collection v3.2.2 solves this issue.

Feel free to reopen if the problem still exists. Thank you.
