### ISSUE TITLE
Create VN use cisco.dnac.sda_virtual_network_v2 does not work

### ISSUE THREAD

**Issue by jianm12007** [cisco-en-programmability/dnacenter-ansible#26]
cisco.dnac.sda_virtual_network_v2 mandatory parameter include virtualNetworkName and virtualNetworkType, both are string type. After check the API from DNAC, the mandatory parameters are virtualNetworkName and isGuestVirtualNetwork which is a boolean type.

Looks like cisco.dnac.sda_virtual_network_v2 does not has isGuestVirtualNetwork parameter support.

**Comment by wastorga** [comment]
Hi @jianm12007. Thanks.
We are working on updating the collection and the SDK that this collection uses.
We will update you when that's done.

**Comment by wastorga** [comment]
Hi, @jianm12007. Yesterday, we updated the collection.

The 3.2.3 version (of this collection) has the requested change and supports DNAC version 2.2.2.3. The SDK requirement for it changed from 2.3.1 to 2.3.3.

The new version 4.0.0 (of this collection) supports DNAC version 2.2.3.3 and has new modules. The SDK requirement for it changed from 2.3.3 to 2.4.0.
