### ISSUE TITLE
missing value for `idempotent` in call to `dnac_argument_spec`

### ISSUE THREAD

**Issue by jandiorio** [cisco-en-programmability/dnacenter-ansible#3]
The function for generating the arg_spec has a flag named `idempotent` which has a default value of `False`.  This value appears to control which values are used for `state` such as [create, delete, update, query] vs [present, absent, query]. 

At the action plugin level, the value of state is used to control execution.   When setting state in the arg_spec the call must pass `idempotent=True` for action plugins that are intended to be idempotent.  

An example is the `site.py` plugin.  the logic filters execution based on the idempotent states of [present, absent, query] but when getting the value doesn't provide `idempotent=True` so the values are limited to [create, delete, update, query]. 

It seems a flag indicating if the plugin is idempotent or not would work. 

```python
IDEMPOTENT=True

...
argument_spec.update(dict(state=dnac_argument_spec(idempotent=IDEMPOTENT).get("state")))
```

**Comment by racampos** [comment]
Fixed in version 1.0.1. Thanks @jandiorio.
