### ISSUE TITLE
Use cisco.dnac.site_create to create building report error

### ISSUE THREAD

**Issue by jianm12007** [cisco-en-programmability/dnacenter-ansible#30]
When I use cisco.dnac.site_create to create building, and I define latitude and longitude as vars. When ansible playbook run, it will always report error as below:

TASK [Create Buildings] ****************************************************************************************************************************
failed: [10.74.83.21] (item={'name': 'SHA-17', 'latitude': 31.2, 'longitude': 121.4, 'parentName': 'Global/Shanghai'}) => {"ansible_loop_var": "item", "item": {"latitude": 31.2, "longitude": 121.4, "name": "SHA-17", "parentName": "Global/Shanghai"}, "msg": "An error occured when executing operation. The error was: {'type': 'building', 'site': {'building': {'latitude': '31.2', 'longitude': '121.4', 'name': 'SHA-17', 'parentName': 'Global/Shanghai'}}} is invalid. Reason: data.site.building.latitude must be number"}

The playbook is really simple, just as below:
********************************
  - name: Create Buildings
    cisco.dnac.site_create:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: "{{dnac_debug}}"
      site:
        building:
          latitude: "{{ item.latitude | int }}"
          longitude: "{{ item.longitude | int }}"
          name: "{{item.name}}"
          parentName: "{{item.parentName}}"
      type: building
    with_items: "{{Buildings}}"

The vars defined are as below:
***********************************
Buildings:
  - name: SHA-17
    latitude: 31.2
    longitude: 121.4
    parentName: "Global/Shanghai"

I don't know how to fix this issue. Please help.

**Comment by southcarolinaswampfox** [comment]
I was able to run this module wit Lat/Long. I did not use quotes in the parentName when referencing the path. 

Example: 

    - name: Create building
      cisco.dnac.site_create:
        site:
          building:
            address: string
            latitude: 50
            longitude: 50
            name: "Building1"
            parentName: Global/AreaName
        type: building

**Comment by southcarolinaswampfox** [comment]
jianm12007,

I was able to define them as variables within the same playbook without any issue. Are you doing something differently? I suspect your issue is related to how you're defining the variables. Are you using quotes to define the lat/long? You need them to be integers, so you shouldn't be using quotes. The error you're getting is " is invalid. Reason: data.site.building.latitude must be number"}" which tells me it thinks you're passing it a string instead of an integer. 

This is the basic Playbook I'm using for this below.

---
- name: Playbook Globals
  hosts: dnac_servers
  collections: 
  - cisco.dnac
  gather_facts: no
  vars:
    - dnac_vars: &dnac_vars
        dnac_host: x.x.x.x
        dnac_username: xxxx
        dnac_password: xxxx
        dnac_port: xxxx 
        dnac_version: 2.2.2.3
        dnac_verify: False
        dnac_debug: False 
      # Playbook Variables
      # Site Variables
      area_name: "Area1"
      building_name: "Building1"
      lat: 50
      long: 50
      floor_name: "Floor1"
      
  tasks:
    - name: Create building
      cisco.dnac.site_create:
        <<: *dnac_vars
        site:
          building:
            address: string
            latitude: "{{ lat }}"
            longitude: "{{ long }}"
            name: "{{ building_name }}"
            parentName: Global/{{area_name}}
        type: building

**Comment by wastorga** [comment]
I am closing the issue since it appears to be related to Ansible variables handling rather than the collection itself.
