### ISSUE TITLE
Create VN to SDA Fabric site using cisco.dnac.sda_virtual_network report error 

### ISSUE THREAD

**Issue by jianm12007** [cisco-en-programmability/dnacenter-ansible#31]
When i run ansible-playbook using cisco.dnac.sda_virtual_network to assign VN to sites, I got a error. Below is the debug output:

Response
	Status: 200 - OK
	Headers: 
		Content-Type: application/json
		Content-Length: 408
		Connection: keep-alive
		bapiexecutionid: 9cac1abc-01ad-44bc-b9a1-e681e67af848
		Server: webserver
		Date: Thu, 16 Dec 2021 09:19:01 GMT
		Via: api-gateway
		Cache-Control: no-store
		Pragma: no-cache
		Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:
		X-Content-Type-Options: nosniff
		X-XSS-Protection: 1
		Strict-Transport-Security: max-age=31536000; includeSubDomains
		X-Frame-Options: SAMEORIGIN
	Body:
             {
                 "**status": "failed",**
                 **"description": "Request body is empty or invalid. Please provide valid request object. Invalid JSON   json  1 0 Expected json literal but found eof",**
                 "taskId": null,
                 "taskStatusUrl": "/dna/intent/api/v1/task/null",
                 "executionStatusUrl": "/dna/intent/api/v1/execution-status/9cac1abc-01ad-44bc-b9a1-e681e67af848",
                 "executionId": "9cac1abc-01ad-44bc-b9a1-e681e67af848"
             }

-----------------------------------------------------------
The playbook is simple as below:
---
# Create SDA VN and assign to site Hierarchy.
- hosts: dnac_servers
  vars_files:
    - vars.yml
  connection: local
  gather_facts: no

  tasks:
  - name: Assign VN to each fabric sites.
    cisco.dnac.sda_virtual_network:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: True
      state: present
      virtualNetworkName: "{{item[0].name}}"
      siteNameHierarchy: "{{item[1].parentName}}/{{item[1].name}}"
    with_nested: 
      - "{{VN}}"
      - "{{Floors}}"

**Comment by jianm12007** [comment]
Found the same issue at cisco.dnac.sda_fabric_site.

**Comment by wastorga** [comment]
Feel free to comment to reopen if the problem persists.
