### ISSUE TITLE
delete global ip pool with absent stat is not work

### ISSUE THREAD

**Issue by jianm12007** [cisco-en-programmability/dnacenter-ansible#32]
Playbook is as below:
-----------------------------------
  - name: Delete Global IP Pool
    cisco.dnac.global_pool:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "{{dnac_version}}"
      dnac_debug: true
      state: absent
      id: "4f317cfa-7bb0-40e6-aab7-a94f691317fe"
    register: output

  - name: debug
    debug:
      msg: "{{output}}"

----------------------------------------------------------------
But it not work. 
I have tried the API directory through DNAC. The API works fine.

**Comment by wastorga** [comment]
Hi, @jianm12007.
The module needed more details to delete it in the previous version. So I changed that behavior in version 4.1.1.
