### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: No module named 'ansible_collections.ansible.utils'

### ISSUE THREAD

**Issue by jorgebanegas** [cisco-en-programmability/dnacenter-ansible#4]
<img width="527" alt="Screen Shot 2021-03-22 at 9 53 59 AM" src="https://user-images.githubusercontent.com/22305451/112000612-88666f80-8af4-11eb-9659-2fc09e986590.png">

Receiving this issue when running the example provided in https://galaxy.ansible.com/cisco/dnac.

Looking for ways to solve this bug

**Comment by jorgebanegas** [comment]
ansible 2.9.7
  config file = None
  configured module search path = ['/Users/jbanegas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]

**Comment by racampos** [comment]
You should already have the `ansible.utils` collection as part of your Ansible default installation. But you can always install it manually with `ansible-galaxy collection install ansible.utils`. Please try that and try running the playbook again.

Today I uploaded a new version of the `cisco.dnac` collection. Please execute `ansible-galaxy collection install cisco.dnac:==1.0.2 --force` to upgrade.

**Comment by jorgebanegas** [comment]
![Screen Shot 2021-03-23 at 12 16 08 PM](https://user-images.githubusercontent.com/22305451/112180020-8d4d2100-8bd1-11eb-8295-0e3292f2be2a.png)


receiving this error after changing the state to create (present was not a valid parameter)

**Comment by jorgebanegas** [comment]
works for me now ! thanks
