### ISSUE TITLE
Unable to initiate stack renumber workflow on device claim

### ISSUE THREAD

**Issue by noziwatele** [cisco-en-programmability/dnacenter-ansible#46]
I am using the pnp_device_claim_to_site module to onboard new switch stacks into our environment, including passing through variable data for the Day-0 template, however I would also like to be able to configure the stack details via this module but have not been able to find a way to do this so far. The manual process via the GUI allows us to do this: claim device, step 2 -> configuration: stack details -> select the cabling scheme and serial number of top switch. This will initiate a stack renumber when the switch is onboarded.

**Describe the solution you'd like**
When I manually configure the switch stack renumbering via the GUI, I can see that the following parameters are added to the device (as seen with pnp_device_info), and the associated workflow becomes type: Stacking. It would be good if these parameters could be passed with pnp_device_claim_to_site to initiate this action.

```
workflowParameters:
    cablingScheme: 1A
    topOfStackSerialNumber: FOC2543Z5XX

```

**Describe alternatives you've considered**
I imagine that and alternative could be to create a Stack Renumber workflow and associate it with a pnp_device, but the documentation available is too limited and I can't see clearly how this would be done.

**Additional context**

![image](https://user-images.githubusercontent.com/18530256/153737218-03280722-6789-417d-b266-1d8feb771842.png)

**Comment by zapodeanu** [comment]
We do not have the stack APIs to re-number the switches in a stack. We have only the API to read the stacked switches info.
Please review if the PnP APIs support this option.
