### ISSUE TITLE
WLC claim is not supported.

### ISSUE THREAD

**Issue by aradford123** [cisco-en-programmability/dnacenter-ansible#59]
Claiming a WLC  for PNP requires the following payload:
{"siteId":"288b1b10-4f21-439c-9677-15943133b77c","deviceId":"625f8b3434ac25000b5ae0d4","hostname":"adam","type":"CatalystWLC","imageInfo":{"imageId":"3f84c0b5-f819-4972-acba-daf8e2b8912d","skip":false,"removeInactive":false},"staticIP":"1.1.1.1","subnetMask":"255.255.255.0","gateway":"1.1.1.2","vlanId":"10","ipInterfaceName":"gig2"}

my playbook tries to use these params and gets an error:

- name: claim to site1
    cisco.dnac.pnp_device_claim_to_site:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      siteId: 288b1b10-4f21-439c-9677-15943133b77c
      deviceId: 625f8b3434ac25000b5ae0d4
      hostname: adam
      type: CatalystWLC
      imageInfo:
        imageId: 3f84c0b5-f819-4972-acba-daf8e2b8912d
        skip: false
        removeInactive: false
      staticIP: 1.1.1.1
      subnetMask: 255.255.255.0
      gateway: 1.1.1.2
      vlanId: '10'
      ipInterfaceName: gig2

it generates the following error:

fatal: [dnac_server]: FAILED! => {
    "changed": false,
    "msg": [
        "gateway, ipInterfaceName, staticIP, subnetMask, vlanId. Supported parameters include: imageInfo, siteId, validate_response_schema, type, dnac_port, rfProfile, dnac_version, hostname, dnac_username (user), dnac_host, dnac_verify, configInfo, deviceId, dnac_debug, dnac_password."
    ]
}

**Comment by fmunozmiranda** [comment]
Hey @aradford123, we are working on it, will keep you informed.

**Comment by fmunozmiranda** [comment]
Hi @aradford123 , versions 2.4.9 and 6.4.0 of dnacentersdk and dnacenter-ansible respectively have been released, please try again with those versions and let us know if it works for you.

---
**Additional info**

My testing playbook looks like this.

---

```yml
- hosts: dnac_servers
  vars_files:
    - credentials.yml
  gather_facts: no
  tasks:
  - name: claim to site1
    cisco.dnac.pnp_device_claim_to_site:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      siteId: 288b1b10-4f21-439c-9677-15943133b77c
      deviceId: 625f8b3434ac25000b5ae0d4
      hostname: adam
      type: CatalystWLC
      imageInfo:
        imageId: 3f84c0b5-f819-4972-acba-daf8e2b8912d
        skip: false
        removeInactive: false
      staticIP: 1.1.1.1
      subnetMask: 255.255.255.0
      gateway: 1.1.1.2
      vlanId: '10'
      ipInterfaceName: gig2


    register: result

  - name: Show result
    ansible.builtin.debug:
      msg: "{{ result }}"

**Comment by aradford123** [comment]
awesome thanks for this.. that fixed it!

**Comment by fmunozmiranda** [comment]
A pleasure to help, I will proceed to close the issue.
