### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by 020003** [cisco-en-programmability/dnacenter-ansible#6]
Hi,

could you please include all the parameters in the DNAC login spec documentation?
I just found the dnac_verify in the module_utils code. 
In my opinion it should be documented in the readme to make the use of the modules a bit more easy for new users :).

**Comment by racampos** [comment]
Hello, thanks for the feedback. I have updated the documentation to reflect all the parameters. Please notice that we just released version 2.0.x, which is not backwards compatible with version 1.0.x in terms of the API. Now you have to put your DNAC login credentials in yaml file and use them in your playbooks.

I suggest you do `ansible-galaxy collection install cisco.dnac:==2.0.3 --force` to make sure you are using the latest version.
