### ISSUE TITLE
Assign devices to sites failed

### ISSUE THREAD

**Issue by jianm12007** [cisco-en-programmability/dnacenter-ansible#82]
**Describe the bug**
Using cisco.dnac.site_assign_device to assign devices to sites but failed, with the below message.

TASK [Assign devices to site.] *****************************************************************************************************************************
[WARNING]: This module is currently unmaintained and will be removed in future releases.
ok: [10.100.0.1]

**Expected behavior**
The DNAC version is 2.3.3.5 and installed DNAC collection version is latest 6.6.0.
I run the same playbook at 2.2.3.3 previously and I works without any issue. After upgrade DNAC, the issue happened.
I test this feature from DNAC API try it directly and i works which means it is not a DNAC API issue.

**Playbook**
  - name: Assign devices to site.
    cisco.dnac.site_assign_device:
      dnac_host: "{{dnac_host}}"
      dnac_username: "{{dnac_username}}"
      dnac_password: "{{dnac_password}}"
      dnac_verify: "{{dnac_verify}}"
      dnac_port: "{{dnac_port}}"
      dnac_version: "2.2.3.3"
      dnac_debug: "{{dnac_debug}}"
      siteId: "0a388cbb-1127-46a7-9db9-5f724c9e1b84"
      device:
        - ip: "10.0.200.2"

**Question**
From the warning message, it show this module is currently unmaintained and will be removed in future releases. Which module will provide the same functionality?

**Comment by bvargasre** [comment]
Hi @jianm12007 
For version 2.3.3.0 the documentation changed so the module for version 2.3.3.0 and higher is `assign_device_to_site`, for lower versions it is `site_assign_device`.

**Comment by jianm12007** [comment]
After check to assign_device_to_site, it is works. Please feel free to close this issue.
