### ISSUE TITLE
snmpv2_write_community_credential and snmpv2_read_community_credential fail on create

### ISSUE THREAD

**Issue by chanhale** [cisco-en-programmability/dnacenter-ansible#88]
DNAC Versions Tested:  DNAC 2.3.3.4 & 2.3.4.0
cisco.dnac ansible collection version: 6.6.2
dnacentersdk version: 2.5.5

According to the Ansible DNAC Module documentation, snmpv2_write_community_credential & snmpv2_read_community_credential can both be used to modify or create SNMPv2 Community Credentials in DNAC.  Create and Modify use the same API endpoint. However, create needs a POST and Modify needs a PUT.  It appears that these modules send PUT in all cases, so they can't be used to create SNMPv2 communities in DNAC--only modify.

Here is the task syntax I was using:

    - name: Create SNMPv2 Read Credential
      cisco.dnac.snmpv2_read_community_credential:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        dnac_port: "{{dnac_port}}"
        dnac_debug: "{{dnac_debug}}"
        state: present
        comments: "SNMPv2 Read by Ansible"
        credentialType: "GLOBAL"
        description: "SNMPv2 Read by Ansible"
        readCommunity: "public"

**Here is the -vv output from the run of that task:**

Request
        URL: https://ip:443/dna/intent/api/v1/global-credential/snmpv2-read-community
        Method: PUT
        Headers: 
                User-Agent: python-requests/2.28.1
                Accept-Encoding: gzip, deflate
                Accept: */*
                Connection: keep-alive
                X-Auth-Token: <token>
                Content-type: application/json;charset=utf-8
        Params:
              {}
        Body:
            {
                "comments": "SNMPv2 Read by Ansible",
                "credentialType": "GLOBAL",
                "description": "SNMPv2 Read by Ansible",
                "readCommunity": "public"
            }

Response
        Status: 202 - 
        Headers: 
                Content-Type: application/json;charset=UTF-8
                Transfer-Encoding: chunked
                Connection: keep-alive
                Set-Cookie: JSESSIONID=52EDD0ED4ECC33BD0BDBF33FA1CC0FC8; Path=/apic-em-inventory-manager-service; HttpOnly; Secure; HttpOnly; SameSite=Strict
                Date: Fri, 13 Jan 2023 20:30:19 GMT
                Server: webserver
                x-request-id: e8aefb32462456bfe1834fbfec4292b2
                Via: api-gateway
                Cache-Control: no-store
                Pragma: no-cache
                Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data:
                X-Content-Type-Options: nosniff
                X-XSS-Protection: 1
                Strict-Transport-Security: max-age=31536000; includeSubDomains
                X-Frame-Options: SAMEORIGIN
        Body:
             {
                 "response": {
                     "taskId": "fc4d0398-111c-4478-b310-787af492efef",
                     "url": "/api/v1/task/fc4d0398-111c-4478-b310-787af492efef"
                 },
                 "version": "1.0"
             }
changed: [ip] => {"changed": true, "dnac_response": {"response": {"taskId": "fc4d0398-111c-4478-b310-787af492efef", "url": "/api/v1/task/fc4d0398-111c-4478-b310-787af492efef"}, "version": "1.0"}, "result": "Object updated"} 

**The Task fails on lack of InstanceUuid since that is required for the Update/PUT operation:**

{
    "response": {
        "version": 1673641819100,
        "startTime": 1673641819100,
        "progress": "Global credential update has failed",
        "errorCode": "BadRequest",
        "endTime": 1673641819106,
        "serviceType": "Inventory service",
        "isError": true,
        "failureReason": "Request or its id is empty",
        "rootId": "fc4d0398-111c-4478-b310-787af492efef",
        "instanceTenantId": "608c3366fcb9d524d15fd867",
        "id": "fc4d0398-111c-4478-b310-787af492efef"
    },
    "version": "1.0"
}

So the enhancement request is to make these modules work for creation of SNMP credentials or create new ones that will use POST.

**Comment by bvargasre** [comment]
Hi @chanhale dnacenter-ansible v6.6.3 is available, try this version and close the issue or comment if needed

**Comment by chanhale** [comment]
Works with 6.6.3.  Will Close.
