### ISSUE TITLE
Bug in "cisco.dnac.site_create" module - Latitude and Longitude being sent as Strings

### ISSUE THREAD

**Issue by miarond** [cisco-en-programmability/dnacenter-ansible#90]
**Prerequisites**
* [x] Have you tested the operation in the API directly?  **Yes, it works when using the API directly to DNA Center.**
* [x] Do you have the latest Ansible collection version?  **Yes, the bug appears to be caused by the latest Ansible DNAC Collection**
* [x] Review the [compatibility matrix](https://github.com/cisco-en-programmability/dnacenter-ansible/tree/main#compatibility-matrix) before opening an issue.  **Compatibility is not an issue here, I have tested this successfully using the option "dnac_version: 2.2.3.3"**

**Describe the bug**
In the `cisco.dnac.site_create` module when creating a Building, you are required to specify a Latitude and Longitude value as a Floating Point number.  This creates a challenge in Ansible Playbooks because Jinja expresses every variable value as a String, so you normally must use the `when:` Conditional, along with a Filter, to convert these values to Floats.  Example:

```
    - name: Loop test
      cisco.dnac.site_create:
        dnac_host: <omitted>
        dnac_username: <omitted>
        dnac_password: <omitted>
        dnac_verify: false
        dnac_port: 443
        dnac_version: "2.3.3.0"
        dnac_debug: false
        site:
          building:
            address: "123 Sesame St."
            latitude: "{{ item.latitude }}"
            longitude: "{{ item.longitude }}"
            name: "{{ item.name }}"
            parentName: "Global/Minneapolis, MN"
        type: building
      loop: "{{ buildings }}"
      when:
         - item.latitude | float
         - item.longitude | float
```

Despite using this conditional `when:` clause, the cisco.dnac.site_create module appears to be sending the values as Strings to the DNA Center API.  Here is an example of the Ansible output from using the ***exact*** Playbook Task code above:

```
TASK [Loop test] ***********************************************************************************************************
task path: /tmp/test.yml:12
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dnacentersdk/models/validators/v2_3_3_0/jsd_bce8e6b307ce52dd8f5546fbd78e05ee.py", line 129, in validate
    self._validator(request)
  File "<string>", line 57, in validate
fastjsonschema.exceptions.JsonSchemaValueException: data.site.building.latitude must be number

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/collections/ansible_collections/cisco/dnac/plugins/plugin_utils/dnac.py", line 209, in exec
    response = func(**params)
  File "/usr/lib/python3.10/site-packages/dnacentersdk/api/v2_3_3_0/sites.py", line 292, in create_site
    .validate(_payload)
  File "/usr/lib/python3.10/site-packages/dnacentersdk/models/validators/v2_3_3_0/jsd_bce8e6b307ce52dd8f5546fbd78e05ee.py", line 131, in validate
    raise MalformedRequest(
dnacentersdk.exceptions.MalformedRequest: {'site': {'building': {'address': '123 Sesame St.', 'latitude': '11.111', 'longitude': '-11.111', 'name': 'Building 1', 'parentName': 'Global/Minneapolis, MN'}}} is invalid. Reason: data.site.building.latitude must be number
fatal: [<omitted>]: FAILED! => {
    "changed": false,
    "msg": "An error occured when executing operation. The error was: {'site': {'building': {'address': '123 Sesame St.', 'latitude': '11.111', 'longitude': '-11.111', 'name': 'Building 1', 'parentName': 'Global/Minneapolis, MN'}}} is invalid. Reason: data.site.building.latitude must be number"
}
```

I have found that by changing the `dnac_version` parameter in my playbook from `2.3.3.0` to `2.2.3.3`, the error no longer occurs and the API calls to DNA Center are successful - the buildings are created in the Site Hierarchy.  It appears that the bug is specific to the most recent version(s) of this Ansible Collection, or possibly the underlying DNA Center Python SDK (I'm not sure which is the cause at this point).

**Expected behavior**
The Ansible Collection should respect the data types passed to each module within a Playbook, especially when the DNA Center API is very particular about the data types it expects.  Ideally, the DNA Center Ansible Collection should handle this data type conversion on the backend, in order to improve the user's experience (since this type of conversion is very troublesome in Ansible Playbooks).

**Screenshots**
No screenshots available however, here is the output from a successful run of the Playbook, after the `dnac_version` parameter was changed to `2.2.3.3`:

```
TASK [ansible.builtin.debug] ***********************************************************************************************
task path: /tmp/test.yml:10
ok: [<omitted>] => {
    "buildings": [
        {
            "building_11": null,
            "latitude": 11.11,
            "longitude": 11.11,
            "name": "Building11",
            "parentName": "Global/Factory1"
        },
        {
            "building_12": null,
            "latitude": 12.12,
            "longitude": 12.12,
            "name": "Building12",
            "parentName": "Global/Factory1"
        },
        {
            "building_21": null,
            "latitude": 21.21,
            "longitude": 21.21,
            "name": "Building21",
            "parentName": "Global/Factory2"
        },
        {
            "building_22": null,
            "latitude": 22.22,
            "longitude": 22.22,
            "name": "Building22",
            "parentName": "Global/Factory2"
        },
        {
            "building_31": null,
            "latitude": 31.31,
            "longitude": 31.31,
            "name": "Building31",
            "parentName": "Global/Factory3"
        },
        {
            "building_32": null,
            "latitude": 32.32,
            "longitude": 32.32,
            "name": "Building32",
            "parentName": "Global/Factory3"
        }
    ]
}
Read vars_file 'vars.yml'

TASK [Loop test] ***********************************************************************************************************
task path: /tmp/test.yml:12
ok: [omitted] => (item={'building_11': None, 'name': 'Building11', 'parentName': 'Global/Factory1', 'latitude': 11.11, 'longitude': 11.11}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "dnac_response": {
        "executionId": "44262da2-0515-4e1e-93a5-22822d7d78a5",
        "executionStatusUrl": "/dna/platform/management/business-api/v1/execution-status/44262da2-0515-4e1e-93a5-22822d7d78a5",
        "message": "The request has been accepted for execution"
    },
    "item": {
        "building_11": null,
        "latitude": 11.11,
        "longitude": 11.11,
        "name": "Building11",
        "parentName": "Global/Factory1"
    },
    "result": ""
}
```

**Environment (please complete the following information):**
* Cisco DNA Center Version and patch: **Version 2.3.4.0-70523**
* Ansible Version:
```
ansible-playbook [core 2.13.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.10.9 (main, Dec 12 2022, 17:52:15) [GCC 12.2.1 20220924]
  jinja version = 3.1.2
  libyaml = True
```
* Collection version: **6.6.3**
* OS Version:  **Alpine Linux 3.17 (Docker container)**

**Additional context**

**Comment by miarond** [comment]
@jianm12007 Thanks for the suggestion :)

**Comment by bvargasre** [comment]
Hi @miarond 
###
In `2.3.3.0` it works because in this version it does not check the types of the sent data are the correct ones according to the doc for this endpoint, in fact it sends them as str
But `2.2.3.3` does.

If the variable is defined as a number without quotes, it will be interpreted as a float type `latitude: 11.11`. If it is defined inside quotes ansible will interpret it as a string (str).
`latitude: "{{ item.latitude }}"`
jinja2_native is a setting in the Ansible configuration file (ansible.cfg) that instructs Ansible to use Jinja2 native types in template evaluation.
This means that, instead of automatically converting values to str, Ansible will preserve the original type of the data (int, float, etc.).

And it can be configured by an environment variable or in the ansible.cfg file
Exporting the environment variable
`export ANSIBLE_JINJA2_NATIVE=True`
Or by configuring it in ansible.cfg
``` cfg
[defaults]
jinja2_native=True
```
More info about ansible.cfg
https://docs.ansible.com/ansible/latest/reference_appendices/config.html
